Repository wecode-bootcamp-korea/21-2nd-GroundBnB-frontend, pull requests merged in 2021-07, with the labels that each got.

#7 [21기 박현찬] Add : 구글 지도 커스텀 마커 추가, 카드 컴포넌트 구현 및 라우팅 완료, 중앙 좌표 구하는 기능 구현 중
  .env
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/data/roomData.json
  public/index.html
  src/Components/Card/Card.js
  src/Components/Footer/Footer.js
  src/Components/Header/Header.js
  src/Components/Header/SearchBox/SearchBox.js
  src/Components/Map/Map.js
  src/Pages/Result/Result.js
  src/images/groundbnb.svg
  src/images/mapPoint.svg
  src/images/reviewStar.svg
Labels: Status: 리뷰 요청

#3 [21기 백진수] 수정요청사항 수정 및 예약 폼, 캘린더 기능구현
  .eslintrc.json
  package-lock.json
  package.json
  public/Data/comment.json
  public/Data/room.json
  public/Images/profile1.jpeg
  public/Images/profile2.jpeg
  public/Images/profile3.jpeg
  public/Images/profile4.jpeg
  public/Images/profile5.jpeg
  public/Images/profile6.jpeg
  public/Images/profile7.jpeg
  public/index.html
  src/Components/Calendar/Calendar.css
  src/Components/Calendar/Calendar.js
  src/Components/Calender/Calender.js
  src/Components/Header/Header.js
  src/Components/Modal/Modal.js
  src/Components/ScrollModal/ScrollModal.js
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Header/Header.js
  src/Pages/Detail/Header/ImageModal/ImageModal.js
  src/Pages/Detail/Header/ImageModal/Slider/Slider.js
  src/Pages/Detail/Main/Description/Description.js
  src/Pages/Detail/Main/Facilities/Facilities.js
  src/Pages/Detail/Main/Main.js
  src/Pages/Detail/Main/ReservationForm/CalendarModal/CalendarModal.js
  src/Pages/Detail/Main/ReservationForm/HeadCount/HeadCount.js
  src/Pages/Detail/Main/ReservationForm/ReservationForm.js
  src/Pages/Detail/Main/Review/Comment/Comment.js
  src/Pages/Detail/Main/Review/CommentForm/CommentForm.js
  src/Pages/Detail/Main/Review/Comments/Comments.js
  src/Pages/Detail/Main/Review/EditForm/EditForm.js
  src/Pages/Detail/Main/Review/ModalComment/ModalComment.js
  src/Pages/Detail/Main/Review/ReviewBar/ReviewBar.js
  src/Pages/Detail/Main/Review/ReviewModal/ReviewModal.js
  src/hooks/usePrevious.js
Labels: Status: Conflict 해결 요청, Status: 수정 요청, Status: 추가 기능 구현중

#8 [21기 박현찬] Fix : 충돌 해결
  config.js
  public/data/whereData.json
  src/Components/Card/Card.js
  src/Components/Header/Header.js
  src/Components/Header/SearchBox/LocationInput/LocationInput.js
  src/Components/Header/SearchBox/LocationInput/LocationResult/LocationResult.js
  src/Components/Header/SearchBox/SearchBox.js
  src/Components/Header/SocialLogin/SocialLogin.js
  src/Components/Map/Map.js
  src/Pages/Main/Main.js
  src/Pages/Result/Result.js
  src/config.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중
